# Generated by Django 3.1.3 on 2020-11-05 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fr', models.TextField()),
                ('vo', models.TextField()),
            ],
            options={
                'db_table': 'defs',
            },
        ),
        migrations.CreateModel(
            name='WordType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
            options={
                'db_table': 'word_types',
            },
        ),
        migrations.CreateModel(
            name='CuratedEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fr', models.TextField()),
                ('vo', models.TextField()),
                ('notes', models.TextField()),
                ('word_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='curator.wordtype')),
            ],
            options={
                'db_table': 'entries',
            },
        ),
    ]
