# Generated by Django 3.1.3 on 2020-11-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0002_curatedentry_multiple_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='curatedentry',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
