# Generated by Django 3.1.3 on 2020-11-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0003_curatedentry_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curatedentry',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
